import Head from "next/head";
import Image from "next/image";
import MatrixRain from "../components/matrixrain";

import { About, Work, WorkExperience } from "../sections";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Andrew Reardigans Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <About />
      <WorkExperience />
      <Work />
    </div>
  );
}
