import Head from "next/head";
import Image from "next/image";

import { HeroSection } from "../sections";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Andrew Reardigan's Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
    </div>
  );
}
